version: "3"

services:
  mongo:
    image: mongo:8.0.3
    container_name: mongo
    network_mode: "host"
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: "host"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: "host"
    depends_on:
      - backend
